library(dplyr)
hpc<-tbl_df(read.table("household_power_consumption.txt", sep = ";", na.strings = c("?",""), header = TRUE))
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
days<-filter(hpc, Date == "2007-02-01" | Date == "2007-02-02")
days$Time <- strptime(paste(days$Date, days$Time), format = "%Y-%m-%d %H:%M:%S")
with(days, plot(Time, Global_active_power, ylab = "Global Active Power (kilowatts)", type = "l", xlab=""))
dev.copy(png, file="Plot2.png")
dev.off()