library(dplyr)
hpc<-tbl_df(read.table("household_power_consumption.txt", sep = ";", na.strings = c("?",""), header = TRUE))
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
days<-filter(hpc, Date == "2007-02-01" | Date == "2007-02-02")
days$Time <- strptime(paste(days$Date, days$Time), format = "%Y-%m-%d %H:%M:%S")
png("Plot4.png", width = 480, height=480, type="window")
par(mfrow = c(2,2), mar = c(4,4,2,1), oma=c(0,0,2,0))
with(days, {
    plot(Time,Global_active_power, ylab="Global Active Power", xlab="", type = "l")
    plot(Time, Voltage, ylab="Voltage", xlab="datetime", type = "l")
    with(days, plot(Time, Sub_metering_1, ylab = "Energy sub metering", type = "l", xlab=""))
    with(days,points(Time, Sub_metering_2, col="red", type="l"))
    with(days,points(Time, Sub_metering_3, col="blue", type="l"))
    legend("topright", lty = 1, col = c("black", "blue", "red"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
    plot(Time,Global_reactive_power, ylab="Global_reactive_power", xlab="datetime", type = "l")})
dev.off()