library(dplyr)
hpc<-tbl_df(read.table("household_power_consumption.txt", sep = ";", na.strings = c("?",""), header = TRUE))
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
days<-filter(hpc, Date == "2007-02-01" | Date == "2007-02-02")
days$Time <- strptime(paste(days$Date, days$Time), format = "%Y-%m-%d %H:%M:%S")
png("Plot3.png", width = 480, height=480, type="window")
with(days, plot(Time, Sub_metering_1, ylab = "Energy sub metering", type = "l", xlab=""))
with(days,points(Time, Sub_metering_2, col="red", type="l"))
with(days,points(Time, Sub_metering_3, col="blue", type="l"))
legend("topright", lty = 1, col = c("black", "blue", "red"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()